version: "3"

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.0.0/16

services:

  nats:
    container_name: cn_nats_go_nats_api_example
    image: nats:1.4.1
    expose:
      - "4222"
    ports:
      - "8222:8222"
    hostname: nats-server
    networks:
      - default

  app:
    container_name: cn_go_nats_api_example
    image: golang:1.12.2
    volumes:
      - .:/go/src/Go-Nats-API-Example
    working_dir: /go/src/Go-Nats-API-Example/cmd/GoNatsAPIExample
    command: go run api.go
    environment:
      - GO111MODULE=on
    depends_on:
      - nats
    ports:
      - "8080:8080"
    links:
      - nats
    networks:
      - default